#开发环境配置

server:
  # 服务端口
  port: 8999


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: "root"
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lin_cmsflask?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    #initialization-mode: always


# 开启权限拦截
auth:
  enabled: false

# 开启登录要求验证码
login-captcha:
  enabled: true
  secret: "m49CPM5ak@MDXTzbbT_ZEyMM3KBsBn!h"

# 开启http请求日志记录
request-log:
  enabled: true


logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录 debug
    io.github.talelin.latticy.mapper: error


file-config:
  batchFilesPath:
    - C:/Users/thinkpad/Desktop/servers/coreIndex
    - C:/Users/thinkpad/Desktop/servers/finAnalysisIndex
    - C:/Users/thinkpad/Desktop/servers/growthIndex
    - C:/Users/thinkpad/Desktop/servers/dupontAnalysisIndex
    - C:/Users/thinkpad/Desktop/servers/stockValue
    - C:/Users/thinkpad/Desktop/servers/tecAnalysisIndex
    - C:/Users/thinkpad/Desktop/servers/industryClass
    - C:/Users/thinkpad/Desktop/servers/secBasicIndex
    - C:/Users/thinkpad/Desktop/servers/listingDate
  fileTypes:
    - CWFXZB
    - CZZB
    - DBFXZB
    - GPGZ
    - JSFXZB
    - HYFL
    - ZQJCZB
  uploadFilesMap:
    HXZB: 'C:\Users\thinkpad\Desktop\servers\coreIndex'
    CWFXZB: 'C:\Users\thinkpad\Desktop\servers\finAnalysisIndex'
    CZZB: 'C:\Users\thinkpad\Desktop\servers\growthIndex'
    DBFXZB: 'C:\Users\thinkpad\Desktop\servers\dupontAnalysisIndex'
    GPGZ: 'C:\Users\thinkpad\Desktop\servers\stockValue'
    JSFXZB: 'C:\Users\thinkpad\Desktop\servers\tecAnalysisIndex'
    HYFL: 'C:\Users\thinkpad\Desktop\servers\industryClass'
    ZQJCZB: 'C:\Users\thinkpad\Desktop\servers\secBasicIndex'
    REC8: 'C:\Users\thinkpad\Desktop\servers\coreIndex'
    SSRQ: 'C:\Users\thinkpad\Desktop\servers\listingDate'


