#生产环境配置

server:
  # 服务端口
  port: 8997

spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    username: "mba"
    password: "!IDy_7)ZA-U3"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lin_cmsflask?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8

# 开启权限拦截
auth:
  enabled: true

# 开启登录要求验证码
login-captcha:
  enabled: false
  secret: "m49CPM5ak@MDXTzbbT_ZEyMM3KBsBn!h"

# 开启请求日志记录
logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录 debug
    io.github.talelin.latticy.mapper: error

file-config:
  batchFilesPath:
    - /home/mba/share/coreIndex
    - /home/mba/share/finAnalysisIndex
    - /home/mba/share/growthIndex
    - /home/mba/share/dupontAnalysisIndex
    - /home/mba/share/stockValue
    - /home/mba/share/tecAnalysisIndex
    - /home/mba/share/industryClass
    - /home/mba/share/secBasicIndex
    - /home/mba/share/listingDate
  fileTypes:
    - CWFXZB
    - CZZB
    - DBFXZB
    - GPGZ
    - JSFXZB
    - HYFL
    - ZQJCZB
  uploadFilesMap:
    HXZB: '/home/mba/share/coreIndex'
    CWFXZB: '/home/mba/share/finAnalysisIndex'
    CZZB: '/home/mba/share/growthIndex'
    DBFXZB: '/home/mba/share/dupontAnalysisIndex'
    GPGZ: '/home/mba/share/stockValue'
    JSFXZB: '/home/mba/share/tecAnalysisIndex'
    HYFL: '/home/mba/share/industryClass'
    ZQJCZB: '/home/mba/share/secBasicIndex'
    REC8: '/home/mba/share/coreIndex'
    SSRQ: '/home/mba/share/listingDate'


